# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


variables:
- group: t-gvar1
#- name: AZURE_CLIENT_ID
#- na  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
#  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
#  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 't-service-connection1'
#    scriptType: 'bash'
    scriptLocation: 'inlineScript'
# - script: echo Hello, world! How are you today? %date% - %time%
    inlineScript: |
      echo Hello, world! How are you today?
      date
      echo $(AZURE_CLIENT_ID)
      echo $(AZURE_TENANT_ID)
#    az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID";
#      echo "Setting subscription..."
#      az account set --subscription "$AZURE_SUBSCRIPTION_ID";
#      rolelist=`az role assignment list --all --assignee "fe77cbae-ef30-4f13-88f2-241f33e5e62f" --output json --query '[].{principalName:principalName, roleDefinitionName:roleDefinitionName, scope:scope}'`;
#      echo $rolelist;
#  displayName: 'Run a one-line script'
#variables:
#env:
#  AZURE_CLIENT_ID: $AZURE_CLIENT_ID
#  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
#  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
#  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
#  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)


#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
