# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hello, world! How are you today? %date% - %time%
- script:
    echo Hello, world! How are you today?
    date
#    az login
#    rolelist=`az role assignment list --all --assignee "fe77cbae-ef30-4f13-88f2-241f33e5e62f" --output json --query '[].{principalName:principalName, roleDefinitionName:roleDefinitionName, scope:scope}'`
#    echo $rolelist
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
